# Experimental: w enhance & fine-tune
# Weights: fine_tuned_model/yolo26{size}_trained.pt

name = "enhance_val"
mode = "val"
model = "fine_tuned_model/yolo26n_trained.pt"
model_template = "fine_tuned_model/yolo26{size}_trained.pt"
data = "lod-dataset.v2i.yolo26/data.yaml"
device = 0

[train]
epochs = 50
patience = 15
batch = 8
imgsz = 640

[val]
# Match TensorRT engine export batch for fair .pt vs .engine latency comparison
batch = 1
imgsz = 640

[predict]
source = "dark_rgb"
conf = 0.25

[export]
format = "engine"
quantize = 16
batch = 1

