[project]
name = "raw-clahe"
version = "0.1.0"
description = "GPU-accelerated HDR CLAHE preprocessing"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "imageio>=2.37.3",
    "kornia>=0.8.3",
    "matplotlib>=3.11.0",
    "opencv-contrib-python>=4.13.0.92",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.3",
    "rawpy>=0.27.0",
    "seaborn>=0.13.2",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
